name: Scorecard
description: Scorecard supply-chain security

runs:
  using: composite
  steps:
    - name: Run analysis
      uses: ossf/scorecard-action@08b4669551908b1024bb425080c797723083c031 # v2.2.0
      with:
        results_file: results.sarif
        results_format: sarif
        publish_results: true

    - name: Upload artifact
      uses: actions/upload-artifact@0b7f8abb1508181956e8e162db84b466c27e18ce # v3.1.2
      with:
        name: scorecard_result_files
        path: results.*
        retention-days: 5

    - name: Upload to code-scanning
      uses: github/codeql-action/upload-sarif@00e563ead9f72a8461b24876bee2d0c2e8bd2ee8 # v2.21.5
      with:
        sarif_file: results.sarif
