name: Ansible Molecule
description: Molecule project is designed to aid in the development and testing of Ansible roles

inputs:
  github_token:
    description: GHA token
    required: true
  role_name:
    description: Ansible role name
    required: true
  distro:
    description: Linux distribution
    required: false
    default: "debian12"
  working_directory:
    description: Working directory
    required: false
    default: "."

runs:
  using: composite
  steps:
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.*"

    - name: Install dependencies
      run: "python3 -m pip install ansible molecule molecule-plugins[docker] docker jmespath"
      shell: bash

    - name: Run Molecule
      run: "molecule test"
      working-directory: ${{ inputs.working_directory }}
      shell: bash
      env:
        PY_COLORS: "1"
        ANSIBLE_FORCE_COLOR: "1"
        MOLECULE_DISTRO: ${{ inputs.distro }}
        ROLE_NAME: ${{ inputs.role_name }}
        GHA_TOKEN: ${{ inputs.github_token }}
