name: Checkmarx KICS
description: Static code scan of IaC

inputs:
  path:
    description: Path to scan
    required: false
    default: ""

runs:
  using: composite
  steps:
    - name: Run KICS scan
      uses: checkmarx/kics-github-action@v1.7.0
      with:
        path: "${{ inputs.path }}"
        fail_on: high
        output_formats: "json,sarif"
      continue-on-error: true

    - name: Upload artifact
      uses: actions/upload-artifact@0b7f8abb1508181956e8e162db84b466c27e18ce # v3.1.2
      with:
        name: Result files
        path: results.*
        retention-days: 5

    - name: Upload to code-scanning
      uses: github/codeql-action/upload-sarif@00e563ead9f72a8461b24876bee2d0c2e8bd2ee8 # v2.21.5
      with:
        sarif_file: results.sarif
