name: Checkmarx KICS
description: Static code scan of IaC

inputs:
  path:
    description: Path to scan
    required: false
    default: ""

runs:
  using: composite
  steps:
    - name: Run KICS scan
      uses: checkmarx/kics-github-action@v1.7.0
      with:
        path: "${{ inputs.path }}"
        fail_on: high
        output_formats: "json,sarif"
      continue-on-error: true

    - name: Display report
      run: |
        cat results.json
      shell: bash

    - name: Upload to code-scanning
      uses: github/codeql-action/upload-sarif@v1
      with:
        sarif_file: results.sarif
